package com.epam.jwd.core_final.domain;

//as a result of the mission is generated by a random or entered from the keyboard
public enum MissionResult {
    CANCELLED,
    FAILED,
    PLANNED,
    IN_PROGRESS,
    COMPLETED
}
